/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PruebaMuestraDatosSQL.app.com.View;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import TablaBD.app.com.Conexion;
import TablaBD.app.com.Consulta;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author capis
 */
public class Acceso_SGBD extends javax.swing.JFrame {

    Conexion conexion;
    ArrayList<String> dataBases; 
    /**
     * Creates new form Acceso_SDGB
     */
    public Acceso_SGBD() {
        initComponents();
        this.setSize(new Dimension(275, 260));
        this.setTitle("Access to SGBD");
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        conexion = new Conexion();
        // Para SQL Server
        Conexion.setUsuarioUsed("sa");
        Conexion.setPasswordUsed("237O00526");
        Conexion.setIdSGBD(1);
        // Para MySQL
        /*Conexion.setUsuarioUsed("root");
        Conexion.setPasswordUsed("Anastasio5602");
        Conexion.setIdSGBD(2);*/   
        showSGBD();
    }
        // Asigna el icono de la imagen al estar ejecutandose la interfaz
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("PruebaMuestraDatosSQL/img/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboSGBD = new javax.swing.JComboBox<>();
        jTextUser = new javax.swing.JTextField();
        jTextPassw = new javax.swing.JTextField();
        jBtnClose = new javax.swing.JButton();
        jBtnConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("BD's");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("User:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jComboSGBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboSGBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 30));
        jPanel1.add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));
        jPanel1.add(jTextPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, -1));

        jBtnClose.setText("Close");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, -1));

        jBtnConnect.setText("Conect");
        jBtnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConnectActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConnectActionPerformed
        if (!jComboSGBD.getSelectedItem().toString().equals("") && !jTextUser.getText().isBlank() && !jTextPassw.getText().isBlank()) {
            // Valores para asignar la conexión al SGBD elejido
            Conexion.setBaseUsed(jComboSGBD.getSelectedItem().toString());
            Conexion.setUsuarioUsed(jTextUser.getText().trim());
            Conexion.setPasswordUsed(jTextPassw.getText().trim());
            // Conexion.setIdSGBD(1);
            // conexion = new Conexion("PuntoVenta", jTextUser.getText().trim(), jTextPassw.getText().trim());
        } else if (jComboSGBD.getSelectedItem().toString().equals("MySQL") && !jTextUser.getText().isBlank() && !jTextPassw.getText().isBlank()) {
            // Valores para asignar la conexión al SGBD elejido
            Conexion.setBaseUsed(jComboSGBD.getSelectedItem().toString());
            Conexion.setUsuarioUsed(jTextUser.getText().trim());
            Conexion.setPasswordUsed(jTextPassw.getText().trim());
            // Conexion.setIdSGBD(2);
            // conexion = new Conexion("PuntoVenta", jTextUser.getText().trim(), jTextPassw.getText().trim());
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos faltantes");
            return;
        }
        JOptionPane.showMessageDialog(this, "Estableciendo conexión...");
        this.dispose();
        JFrame interfazDatos = new MuestraDatos1();
        interfazDatos.setVisible(true);
    }//GEN-LAST:event_jBtnConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso_SGBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso_SGBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso_SGBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso_SGBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso_SGBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnConnect;
    private javax.swing.JComboBox<String> jComboSGBD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextPassw;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables
    private void showSGBD(){
        jComboSGBD.removeAllItems();
        dataBases = Consulta.getDataBases(conexion.getConexion(Conexion.getIdSGBD()));    
        for(String dataBase : dataBases){
            jComboSGBD.addItem(dataBase);
        }
    }    
}
